function [h] = GSPTB_AddSignificanceBracket(ax,XPositions,YPosition,Label,...
    Color,LineWidth,FontSize)

    % Validates axes
    if isempty(ax) || ~isgraphics(ax,'axes')
        error('GSPTB:InvalidAxes', ...
            'ax must be a valid axes handle!');
    end

    % Validates horizontal positions
    if ~isnumeric(XPositions) || ~isreal(XPositions) || ...
            ~isequal(size(XPositions),[1 2]) || ...
            any(~isfinite(XPositions)) || ...
            XPositions(1) >= XPositions(2)
        error('GSPTB:InvalidPosition', ...
            ['XPositions must contain two finite, strictly ' ...
             'increasing numeric values!']);
    end

    % Validates vertical position
    if ~isnumeric(YPosition) || ~isreal(YPosition) || ...
            ~isscalar(YPosition) || ~isfinite(YPosition)
        error('GSPTB:InvalidPosition', ...
            'YPosition must be a finite numeric scalar!');
    end

    % Validates label
    if ischar(Label)
        Label = string(Label);
    end

    if ~isstring(Label) || ~isscalar(Label) || ...
            ismissing(Label) || strlength(Label) == 0
        error('GSPTB:InvalidLabel', ...
            'Label must be a non-empty text scalar!');
    end

    % Validates color
    if ~isnumeric(Color) || ~isreal(Color) || ...
            ~isequal(size(Color),[1 3]) || ...
            any(~isfinite(Color)) || ...
            any(Color < 0 | Color > 1)
        error('GSPTB:InvalidColor', ...
            ['Color must be a finite 1-by-3 RGB triplet ' ...
             'with values between 0 and 1!']);
    end

    % Validates line width
    if ~isnumeric(LineWidth) || ~isreal(LineWidth) || ...
            ~isscalar(LineWidth) || ...
            ~isfinite(LineWidth) || LineWidth <= 0
        error('GSPTB:InvalidLineWidth', ...
            'LineWidth must be a positive finite scalar!');
    end

    % Validates font size
    if ~isnumeric(FontSize) || ~isreal(FontSize) || ...
            ~isscalar(FontSize) || ...
            ~isfinite(FontSize) || FontSize <= 0
        error('GSPTB:InvalidFontSize', ...
            'FontSize must be a positive finite scalar!');
    end

    % Derives a short vertical tick length from the current y-range
    YLimits = ylim(ax);
    TickHeight = 0.02 * diff(YLimits);

    % Preserve hold state
    WasHeld = ishold(ax);
    hold(ax,'on');

    % Draws bracket
    hLine = line(ax, ...
        [XPositions(1),XPositions(1), ...
         XPositions(2),XPositions(2)], ...
        [YPosition-TickHeight,YPosition, ...
         YPosition,YPosition-TickHeight], ...
        'Color',Color, ...
        'LineWidth',LineWidth);

    % Adds annotation
    hText = text(ax,mean(XPositions),YPosition,Label, ...
        'Color',Color, ...
        'FontSize',FontSize, ...
        'HorizontalAlignment','center', ...
        'VerticalAlignment','bottom', ...
        'Clipping','off');

    % Restore hold state
    if ~WasHeld
        hold(ax,'off');
    end

    % Return handles
    h.Axes = ax;
    h.Line = hLine;
    h.Text = hText;
end